global:
  scrape_interval: 15s # Default scrape interval
  external_labels:
    monitor: 'mycv-rest-api-monitor'

scrape_configs:
  - job_name: 'prometheus' # Job to scrape Prometheus metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-actuator'
    metrics_path: '/api/actuator/prometheus' # Job to scrape application metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8401']
